print(ord('v'))
print(ord('i'))
print(ord('n'))
print(ord('e'))
print(ord('e'))
print(ord('t'))
print()
print(ord('V'))
print(ord('I'))
print(ord('N'))
print(ord('E'))
print(ord('E'))
print(ord('T'))

